### ISSUE TITLE
Nosuchmethoderror:

### ISSUE THREAD

**Issue by sudheera8** [flower-platform/ArduinoCore-samd-OTA#1]
Hi

I am new to OTA and I am trying to do OTA on my arduino Zero board using FlowerOTA platform. But when I try to compile my code using the flower platform plugin in arduino ide 1.6.12 verison I get the following error:

Exception in thread "Thread-18" java.lang.NoSuchMethodError: processing.app.Sketch.build(ZZ)Ljava/lang/String;
	at org.flowerplatform.flowerino.otaupload.OtaUploadDialog.lambda$0(OtaUploadDialog.java:379)
	at java.lang.Thread.run(Thread.java:745)

Kindly guide me through this.

**Comment by Emmanul123456** [comment]
Hello Friend
I'm new to the topic of programming I can not correctly understand the Bootloader, I would like to know if you managed to compile correctly, I am interested in developing a bootloader to upload sketch but in the plate SparkFun SAMD21 Dev Breakout by GPRS, you would be so kind to be able to indicate me, thank you.

**Comment by elvaigh** [comment]
I'm too interested in developing a bootloader for Atmel Samd21 any help? Thanks!
